#!/bin/bash

set -e

SRC_DIR="$(dirname -- "$(readlink -f -- "$0")")"
RUN_DIR=${SRC_DIR}/run
FISH_DIR=${RUN_DIR}/fish-speech

export OLLAMA_KEEP_ALIVE=-1
export OLLAMA_HOST=0.0.0.0:5000
export OLLAMA_KV_CACHE_TYPE=q8_0
export OLLAMA_FLASH_ATTENTION=1
