#!/bin/bash

set -e

SRC_DIR="$(dirname -- "$(readlink -f -- "$0")")"
RUN_DIR=${SRC_DIR}/run
FISH_DIR=${RUN_DIR}/fish-speech
SD_DIR=${RUN_DIR}/stable-diffusion-webui-reForge
AIME_DIR=${RUN_DIR}/aime-api-server
AIME_SD_DIR=${AIME_DIR}/aime-api_stable_diffusion_3_5

export OLLAMA_KEEP_ALIVE=-1
export OLLAMA_HOST=earthsea.local:5000
