#!/bin/bash

source commonEnv

cd ${AIME_DIR}
source venv/bin/activate
gnome-terminal --tab -e "python run_api_server.py"

echo "Waiting for AIME server initialization..."
sleep 10

cd ${AIME_SD_DIR}
python main.py --model=models/sd3.5_medium.safetensors
