#!/bin/bash

source commonEnv

cd ${RUN_DIR}
source ${RUN_DIR}/venv/bin/activate

pip install openai
pip install openai-whisper
pip install tk
pip install opencv-python
pip install face-recognition
pip install imageio[ffmpeg]
pip install shelves
pip install pydub
