#!/bin/bash

source commonEnv
source ${RUN_DIR}/venv/bin/activate

sudo apt install libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev \
    libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk \
    libharfbuzz-dev libfribidi-dev libxcb1-dev

cd ${RUN_DIR}
git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git
cd ${SD_DIR}
ln -s ../venv venv
