#!/bin/bash
# Requires listenOllama already running

source commonEnv

cp -r ~/Dropbox/schizolalia/samples/bubbles ${FISH_DIR}/references
cp -r ~/Dropbox/schizolalia/images/bubbles ${RUN_DIR}/images

cd ${SRC_DIR}
ollama create bubbles -f models/bubbles
