#!/bin/bash

source commonEnv

cd ${RUN_DIR}
git clone https://github.com/jsichi/fish-speech.git

source ${RUN_DIR}/venv/bin/activate

cd ${FISH_DIR}
pip install -e .
pip install "pydantic>=2"

hf auth login
hf download fishaudio/openaudio-s1-mini --local-dir checkpoints/openaudio-s1-mini
mkdir -p ${FISH_DIR}/references
