#!/bin/bash

source commonEnv

cd ${RUN_DIR}
source ${RUN_DIR}/venv/bin/activate

pip install pvporcupine
pip install pvcobra
pip install pvrecorder

mkdir -p ${RUN_DIR}/wakewords

wget -O ${RUN_DIR}/wakewords/porcupine_params_ko.pv \
    https://github.com/Picovoice/porcupine/raw/refs/heads/master/lib/common/porcupine_params_ko.pv
