#!/bin/bash

source commonEnv

sudo apt install \
     curl portaudio19-dev libsox-dev ffmpeg python3-tk python-is-python3 python3-venv \
     build-essential python-dev-is-python3

mkdir -p ${RUN_DIR}
cp ${SRC_DIR}/example.ini ${RUN_DIR}/config.ini
cd ${RUN_DIR}
python -m venv venv
source ${RUN_DIR}/venv/bin/activate

pip install -U "huggingface_hub[cli]"
